### ISSUE TITLE
Where does config go?

### ISSUE THREAD

**Issue by labob246** [IDmedia/hass-unraid#17]
I am getting the following error when starting hass-unraid from the docker section of unraid.

Traceback (most recent call last):
  File "/app/main.py", line 284, in <module>
    for unraid_config in config.get('unraid'):
TypeError: 'NoneType' object is not iterable

I did create a data directory and placed the following config.yaml there
unraid:
- name: tower
  host: 192.168.68.105
  port: 80
  ssl: False
  username: ***
  password: ***
  scan_interval: 30

mqtt:
  host: 192.168.68.117
  port: 1883
  username: ***
  password: ***

What am i doing wrong?

**Comment by elmoret** [comment]
probably good to post what you found, as I ran into the same issue. No extra data directory needed in my case, just right in the hass-unraid folder.
