### ISSUE TITLE
Unused disks

### ISSUE THREAD

**Issue by emilgil** [IDmedia/hass-unraid#5]
Hey, great addon! Is there any chance one could hide unused disks? I only have 3 data disks and 1 parity disk but this addon creates 22 data disk sensors in Home Assistant. Also, adjustable polling interval would be nice.

**Comment by IDmedia** [comment]
> Hey, great addon! Is there any chance one could hide unused disks? I only have 3 data disks and 1 parity disk but this addon creates 22 data disk sensors in Home Assistant. Also, adjustable polling interval would be nice.

1. The way I would "hide" them is to just not include them in the lovelace markup.
2. You can alter the polling interval in the config by altering: `scan_interval: 30`
