### ISSUE TITLE
not everything is showing up

### ISSUE THREAD

**Issue by thatkookooguy** [IDmedia/hass-unraid#6]
noticed a few problems in my specific setup:
1. not all shares are loaded. only the anime share is being loaded for some reason (I have much more)
2. if I start the docker with auto start, sometimes shares are not loaded at all
3. missing power and fan info (tried installing some dynamix plugins but that didn't help
4. missing docker entities besides `docker_usage`

Other than that, everything else looks good (I currently just put the CPU usage in the FAN and PWR fields)

![image](https://github.com/IDmedia/hass-unraid/assets/10427304/1a1502d6-b237-4b24-ae0d-9629009171bf)

This is what I see in MQTT Explorer:
![image](https://github.com/IDmedia/hass-unraid/assets/10427304/718ba587-c416-4877-9259-d5061867b2fa)

**Comment by IDmedia** [comment]
I also noticed some issues with shares, but only on one of my unraid servers. I'll investigate, but not before after the summer

**Comment by IDmedia** [comment]
https://github.com/IDmedia/hass-unraid/pull/13
I hope this resolves the issue. Please let me know if it persists
