### ISSUE TITLE
cant import template in GUI lovelace

### ISSUE THREAD

**Issue by woodenapple** [IDmedia/hass-unraid#8]
at first: awesome work!

i cant integrate the lovelace card, due to not being able to include 
"button_card_templates: !include_dir_merge_named lovelace/templates/button_card"
to the top of the dashboard
since i use the gui configuration, i dont have a lovelace.yaml file to add the line

is there a workaround? i tried adding "decluttering_templates:" and adding your tamplates, but it doesnt seem to work

thank you for your integration!

**Comment by Shiroe93** [comment]
+1 same for me unfortunately

**Comment by Shiroe93** [comment]
Awesome
Thank you

**Comment by Kosh42** [comment]
+1

**Comment by IDmedia** [comment]
The workaround is to go to `Edit (top right)->Raw configuration editor` and then paste the templates in there instead:

```
button_card_templates:
  button_unraid_disk:
    ....
  button_simple_bar:
    ...
  button_network_share:
    ...
```

I personally prefer to have them in individual files, but Home Assistant only supports the !include.. commands in YAML mode.
